pipeline {
    agent any
    
    tools{
			maven 'maven3.6.3'
			jdk 'jdk1.8'
	}
    
    stages {
        stage('Clone') {
            steps {
                git 'git@techlab.cyware.com:cyware/cftr-automation-suite.git'
            }
        }
        stage('Automation testing'){
            steps{
                 sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                    cd cftr-suite-automation
                    mvn clean test
                '''
            }
        }
        stage('Publish Reports')
        {
            steps{
                 publishHTML target: [
		            allowMissing: false,
		            alwaysLinkToLastBuild: false,
		            keepAll: true,
		            reportDir: 'cftr-suite-automation/target/surefire-reports/',
		            reportFiles: 'ExtentReport.html',
		            reportName: 'ExtentReport'
		          ]
            }
        }
    }
}